openapi: 3.1.0
info:
  title: AI Text & Plagiarism Detector
  version: "1.6.0"
servers:
  - url: https://ai-detection-1-197w.onrender.com
paths:
  /analyze:
    post:
      operationId: analyzeText
      summary: Analyze text and return JSON summary and sentence-level labels
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
                  description: Plain text to analyze
      responses:
        "200":
          description: Analysis done
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
                    properties:
                      ai_score: { type: integer }
                      plagiarism_score: { type: integer }
                      human_score: { type: integer }
                  sentences:
                    type: array
                    items:
                      type: object
                      properties:
                        index:   { type: integer }
                        text:    { type: string }
                        label:   { type: string, enum: [ai, plag, human] }
                        score:   { type: number, nullable: true }
                        source:  { type: string, nullable: true }
  /preview:
    post:
      operationId: previewHtml
      summary: Return a simple HTML preview for website testing (not for ChatGPT display)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        "200":
          description: HTML page
          content:
            text/html:
              schema:
                type: string
components:
  schemas: {}
