openapi: 3.1.0
info:
  title: AI Text & Plagiarism Detector
  version: "1.7.0"
servers:
  - url: https://ai-detection-1-197w.onrender.com
paths:
  /analyze:
    post:
      operationId: analyzeText
      summary: Analyze text; return JSON summary and sentence-level labels with optional plagiarism sources
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
                source_texts:
                  type: array
                  items: { type: string }
                  description: Optional reference texts to check against
                source_urls:
                  type: array
                  items: { type: string }
                  description: Optional URLs to fetch and compare against
                plag_threshold:
                  type: integer
                  default: 85
                  minimum: 50
                  maximum: 100
      responses:
        "200":
          description: Analysis done
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
                    properties:
                      ai_score: { type: integer }
                      plagiarism_score: { type: integer }
                      human_score: { type: integer }
                  sentences:
                    type: array
                    items:
                      type: object
                      properties:
                        index: { type: integer }
                        text: { type: string }
                        label: { type: string, enum: [ai, plag, human] }
                        ai_like: { type: boolean, nullable: true }
                        plag_score: { type: integer, nullable: true }
                        source: { type: string, nullable: true }
                        source_snippet: { type: string, nullable: true }
  /preview:
    post:
      operationId: previewHtml
      summary: HTML preview for website UI (not for ChatGPT)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeRequestLike'
      responses:
        "200":
          description: HTML page
          content:
            text/html:
              schema:
                type: string
components:
  schemas:
    AnalyzeRequestLike:
      type: object
      required: [text]
      properties:
        text: { type: string }
        source_texts:
          type: array
          items: { type: string }
        source_urls:
          type: array
          items: { type: string }
        plag_threshold:
          type: integer
          default: 85
          minimum: 50
          maximum: 100
