openapi: 3.0.3
info:
  title: AI Text & Plagiarism Detector
  version: "1.5.0"
servers:
  - url: https://ai-detection-1-197w.onrender.com
paths:
  /analyze:
    post:
      operationId: analyzeText
      summary: Analyze text and return JSON summary plus color-highlighted HTML
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
                  description: Plain text to analyze
      responses:
        "200":
          description: Analysis done
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
                    properties:
                      ai_score:
                        type: integer
                      plagiarism_score:
                        type: integer
                      human_score:
                        type: integer
                  highlighted_html:
                    type: string
                    description: Safe HTML snippet to render with innerHTML
  /preview:
    post:
      operationId: previewHtml
      summary: Returns a complete HTML page with embedded summary chips and highlighted text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        "200":
          description: HTML page
          content:
            text/html:
              schema:
                type: string
components: {}
