openapi: 3.1.0
info:
  title: AI Text & Plagiarism Detector
  version: "1.3.0"
servers:
  - url: https://ai-detection-1-197w.onrender.com
paths:
  /healthz:
    get:
      operationId: healthCheck
      summary: Check if API is running
      responses:
        "200": { description: OK }
  /analyze:
    post:
      operationId: analyzeText
      summary: Analyze text and return HTML highlights + spans
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text: { type: string }
                ai_threshold: { type: number, default: 0.65 }
                return_html: { type: boolean, default: true }
                plagiarism: { type: boolean, default: true }
                show_only_flagged: { type: boolean, default: false }
                show_score_badges: { type: boolean, default: true }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary: { type: object }
                  spans: { type: array, items: { type: object } }
                  html_preview: { type: string }
  /report:
    post:
      operationId: downloadReport
      summary: Generate a downloadable PDF report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text: { type: string }
                ai_threshold: { type: number, default: 0.65 }
                plagiarism: { type: boolean, default: true }
                show_only_flagged: { type: boolean, default: false }
      responses:
        "200":
          description: PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
